### PR TITLE
Replaced Active Customer instance with Identity Framework logic

### PR DESCRIPTION
**Pull request by delaineackerman**
## Pull Request Description

Added user identity using Identity Framework 

## Steps To Test

1. `git prune`
1. `git checkout ddw-user-identity`
1. Make sure that you can login, add a product to your cart, and see it in the shopping cart.

### CODE REVIEW

**Review by thrashMoneyVillainare — COMMENTED** [review]
i believe this is good. 🎲

**Review by JamsDuke — COMMENTED** [review]
:feelsgood:

**Comment by HubDub** [comment]
I am able to add products to the cart and can see the new order in the DB. looks good.

**Review by Jgregnier — APPROVED** [review]
🇹🇫

**Pull request merged**
