### PR TITLE
Changed links in nav bar

### PR DESCRIPTION
**Pull request by Jgregnier**
Changed the links in the nav bar and corrected site.js errors.

### CODE REVIEW

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Comment by csmalley89** [comment]
💯 🇺🇸

**Comment by HubDub** [comment]
these links work for me.

**Review by thrashMoneyVillainare — COMMENTED** [review]
:south_georgia_south_sandwich_islands:

**Review by JamsDuke — APPROVED** [review]
:feelsgood:

**Pull request merged**
